import "./globals.css";
import Image from "next/image";

export const metadata = {
  title: "Perforación direccional de México",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>
        <header>
          <header>
              <Image
                src="/images.png"
                alt="logo empresa"
                width={200}
                height={200}
              ></Image>
          </header>
        </header>
        <footer>
          
        </footer>
        {children}
      </body>
    </html>
  );
}
