import "./globals.css";
import "../../public/css/image.css";
import Link from "next/link";

export const metadata = {
  title: "Perforación direccional de México",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>
        <header>
          <div className="text-white absolute z-10 w-full">
            <div className=" flex flex-row justify-around bg-red-700 py-9 ">
              <div className="flex flex-rows h-9 items-center">
                <p>LOGO</p>
              </div>
              <div className="flex flex-rows h-9 items-center">
                <img
                  src="assets/location.png"
                  alt=""
                  width="35px"
                  className="pr-2"
                />
                <p>Direccion </p>
              </div>
              <div className="flex flex-rows h-9 items-center">
                <img
                  src="assets/phone.png"
                  alt=""
                  width="35px"
                  className="pr-2"
                />
                <p>Telefono </p>
              </div>
            </div>
            <div className="flex w-full justify-center">
              <div className="flex flex-row  justify-around bg-black text-white w-3/4 h-14 items-center relative bottom-5  shadow-xl">
                <Link href="/">INICIO</Link>
                <Link href="/nosotros">NOSOTROS</Link>
                <Link href="/servicios">SERVICIOS</Link>
                <Link href="/proyectos">PROYECTOS</Link>
                <Link href="/contacto">CONTACTO</Link>
              </div>
            </div>
          </div>
        </header>
        {children}
        <footer>
          <div className=" flex flex-row justify-around py-5 bg-red-700 text-white">
            <div>
              <h1 className="pb-3 pt-2 text-lg">
                Perforación Direccional de México
              </h1>
              <div className="flex flex-row py-2 items-center">
                <img src="assets/location.png" alt="" width="25px" />
                <p className="px-2">Dirección</p>
              </div>
              <div className="flex flex-row py-2 items-center">
                <img src="assets/phone.png" alt="" width="25px" />
                <p className="px-2">Telefono</p>
              </div>
              <div className="flex flex-row py-2 items-center">
                <img src="assets/gmail.png" alt="" width="25px" />
                <p className="px-2">correo</p>
              </div>
            </div>
            <div>
              <h1 className="pb-3 pt-2 text-lg"> Secciones</h1>
              <p>Inicio</p>
              <p>Nosotros</p>
              <p>Servicios</p>
              <p>Proyectos</p>
              <p>Contacto</p>
            </div>
            <div>
              <h1 className="pb-3 pt-2 text-lg">Servicios</h1>
              <p>Perforación Direccional Dirigida</p>
              <p>Georradar</p>
              <p>Cracking</p>
              <p>Termofusión</p>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
